# Generated by Django 5.2.7 on 2025-10-03 16:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_active', 'full_name'],
                'indexes': [models.Index(fields=['full_name'], name='worklog_wor_full_na_692381_idx'), models.Index(fields=['is_active'], name='worklog_wor_is_acti_95ad96_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(default='шт', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='worklog_wor_is_acti_7e8d32_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Сколько сделали', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('source_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('source_message_id', models.BigIntegerField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='worklog.worker')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='worklog.worktype')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['work_date', 'worker'], name='worklog_wor_work_da_16fa58_idx'), models.Index(fields=['worker', 'created_at'], name='worklog_wor_worker__e4476e_idx')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'work_type', 'work_date'), name='uniq_worker_worktype_day')],
            },
        ),
    ]
